<a href="https://colab.research.google.com/github/min207/ESAA/blob/main/ESAA_220916.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **01. 머신러닝의 개념**
---
- **머신러닝**: 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법
- 소프트웨어 코드로 로직을 구성하여 일정한 패턴을 찾기 어려운 경우, 데이터를 기반으로 숨겨진 패턴을 인지해 머신러닝으로 해결 가능
- 데이터 마이닝, 영상/음성 인식, 자연어 처리 등 난이도와 개발 복잡도가 너무 높아지는 문제를 해결 가능

#### **> 머신러닝의 분류**
- **지도학습**
  + 분류
  + 회귀
  + 추천 시스템
  + 시각/음성 감지/인지
  + 텍스트 분석, NLP

- **비지도학습**
  + 클러스터링
  + 차원 축소

- **강화 학습**

#### **> 데이터 전쟁**
- 머신러닝은 데이터에 매우 의존적이라는 단점이 있음
  - Garbage in, garbage out
- 따라서 데이터를 이해하고 효율적으로 가공, 처리, 추출하여 최적의 데이터를 기반으로 알고리즘을 구동할 수 있도록 준비하는 능력이 중요함

#### **> 파이썬과 R 기반의 머신러닝 비교**
- R
  + 통계 전용 프로그램 언어
  + 다양하고 많은 통계 패키지 보유

- 파이썬
  + 다양한 영역에서 사용되는 개발 전문 프로그램 언어
  + 유수의 딥러닝 프레임워크인 텐서플로, 케라스, 파이토치 등 지원



# **02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지**
- 머신러닝 패키지: 사이킷런, 텐서플로, 케라스 등
- 행렬/선형대수/통계 패키지: 넘파이, 사이파이 등
- 데이터 핸들링: 판다스 등
- 시각화: 맷플롯립, 시본 등



# **03. 넘파이(NumPy)**
- Numerical Python
- 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지
- 루프 없이 대량 데이터의 배열 연산 가능/ 데이터 핸들링 기능 제공
---
#### **넘파이 ndarray 개요**
- 넘파이 모듈 임포트
```python
import numpy as np
```
  + 넘파이 모듈 임포트 / np(약어)로 표현
  + 넘파이의 기반 데이터 타입: ndarray
  + 다차원 배열을 쉽게 생성하고 다양한 연산 수행 가능

- array() 함수
  + 다양한 인자를 입력 받아서 ndarray로 변환
  + ndarray의 shape 변수는 ndarray의 차원과 크기, 열과 행을 튜플 형태로 나타냄
```python
array1 = np.array([element1, element2])
```

In [1]:
import numpy as np

array1 = np.array([1,2,3]) # 1X3 배열
print('array1 type: ', type(array1))
print('array1 array 형태: ', array1.shape)  #row 1개, column 3개, 1차원 데이터

array2 = np.array([[1,2,3],[2,3,4]]) # 2X3 배열
print('array2 type: ', type(array2))
print('array2 array 형태: ', array2.shape) #row 1개, column 3개, 1차원 데이터

array3 = np.array([[1,2,3]]) # 1X3 배열. 대괄호가 2개
print('array3 type: ', type(array3))
print('array3 array 형태: ', array3.shape) # row 1개, column 3개, 2차원 데이터

array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)


  - 이때, 각 array의 차원을 ndarray.ndim을 이용해 확인 가능

In [2]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


#### **ndarray의 데이터 타입**
- ndarray내의 데이터 값은 숫자, 문자열, 불 값 등 모두 가능
- ndarray내의 데이터 타입은 연산의 특성상 같은 데이터 타입만 가능
- ndarray내의 데이터 타입은 dtype 속성으로 확인 가능

In [3]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


- 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용

In [4]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype) #숫자형 값을 모두 문자열 값으로 변환

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) #int가 float로 변환

['1' '2' 'test'] <U21
[1. 2. 3.] float64


- asype() 메서드
  + ndarray 내 데이터값의 타입 변경
  + 인자로 원하는 타입을 문자열로 지정
  + 메모리 절약하는 데에 주로 사용

In [5]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


#### **ndarray를 편리하게 생성하기 - arange, zeros, ones**

- arange() 함수
  + range() 함수와 유사한 기능
  + 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환

- zeros() 함수
  + 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray 반환

- ones() 함수
  + 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray 반환
  + dtype을 지정하지 않으면 float64형의 데이터를 기본값으로 가짐

In [9]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype ='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#### **ndarray의 차원과 크기 변경**
- reshpae() 메서드
  + ndarray를 특정 차원 및 크기로 변환
  + 지정된 사이즈로 변경 불가 시 오류 발생
  + 인자로 -1을 사용하여 자동으로 지정값에 알맞는 행 또는 열이 되게하여 효율적인 사용 가능

In [10]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1. reshpae(4,3)  #오류 발생

AttributeError: ignored

In [12]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [13]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)   #10은 4로 나누어떨어지지 않아서 오류 발생

ValueError: ignored

- 원본 ndarray가 어떤 형태라도 reshape(-1,1)는 2차원이고 column이 1개인 ndarray로 변환
  + stack이나 concat으로 여러 개의 ndarray를 결합할 때, ndarray의 형태를 통일하기 위해 유용하게 사용 가능

In [14]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2)) # 3차원 배열
print('array3d: \n', array3d.tolist())

# 3차원 ndarray를 2차원으로 변환
array5 = array3d.reshape(-1,1)
print('array5 : \n', array5.tolist()) # list로 변경
print('array5 shape:', array5.shape)
print()
# 1차원 ndarray를 2차원으로 변환
array6 = array1.reshape(-1,1)
print('array6 : \n', array6.tolist()) # list로 변경
print('array6 shape:', array6.shape)

array3d: 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)

array6 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


#### **넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱**
- 특정 데이터만 추출
```python
value = array[i]
```
  + 인덱스 값을 지정하면 해당 위치의 데이터 반환
  + 인덱스는 0부터 시작 / -1은 맨 뒤의 값을 의미
  + 단일 인덱스를 이용해 ndarray 내의 데이터값 수정 가능

In [16]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

print('맨 뒤의 값:',array1[-1],'맨 뒤에서 두 번째 값:',array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [17]:
#ndarrya 내의 데이터 값 수정
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [18]:
# n차원 ndarray에서 단일 값 추출(n이 2 이상일 때)
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3,3)
print(array2d)

# axis 0 : row 방향, axis 1 : column 방향
print('(row=0, col=0) index가 가리키는 값 : ', array2d[0,0])
print('(row=0, col=1) index가 가리키는 값 : ', array2d[0,1])
print('(row=1, col=0) index가 가리키는 값 : ', array2d[1,0])
print('(row=2, col=2) index가 가리키는 값 : ', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index가 가리키는 값 :  1
(row=0, col=1) index가 가리키는 값 :  2
(row=1, col=0) index가 가리키는 값 :  4
(row=2, col=2) index가 가리키는 값 :  9


- 슬라이싱
```python
array2 = array1[a:b]
```
  + 연속된 인덱스상의 ndarray를 추출
  + 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터 반환
  + 시작, 종료 인덱스는 생략 가능
  + 2차원 ndarray에서는 ,를 사용해 row, col 각각의 인덱스에 슬라이싱 적용

In [20]:
from numpy.core.getlimits import array
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [22]:
array1 = np.arange(1,10)
array4 = array1[:3] #처음부터 세번째 값까지
print(array4)

array5 = array1[3:] #네번쨰 값부터 끝까지
print(array5)

array6 = array1[:] #전체 데이터 출력
print(array6) 

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [23]:
# 2차원 ndarray에서의 슬라이싱

array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d : \n', array2d)

print('aarray2d[0:2,0:2] : \n', array2d[0:2,0:2])
print('aarray2d[1:3,1:3] : \n', array2d[1:3,1:3])
print('aarray2d[1:3,:] : \n', array2d[1:3,:])
print('aarray2d[:,:] : \n', array2d[:,:])
print('aarray2d[:2,1:] : \n', array2d[:2,1:])
print('aarray2d[:2,0] : \n', array2d[:2,0]) #축 한쪽에만 슬라이싱 적용/ 다른 축에는 단일 값 인덱스 적용 가능

array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
aarray2d[0:2,0:2] : 
 [[1 2]
 [4 5]]
aarray2d[1:3,1:3] : 
 [[5 6]
 [8 9]]
aarray2d[1:3,:] : 
 [[4 5 6]
 [7 8 9]]
aarray2d[:,:] : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
aarray2d[:2,1:] : 
 [[2 3]
 [5 6]]
aarray2d[:2,0] : 
 [1 4]


In [24]:
print(array2d[0]) # 1차원 데이터 반환
print(array2d[1])
print('aarray2d[0].shape :', array2d[0].shape, 'aarray2d[1].shape :', array2d[1].shape) 

[1 2 3]
[4 5 6]
aarray2d[0].shape : (3,) aarray2d[1].shape : (3,)


- 팬시 인덱싱
  + 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해서 해당 위치의 데이터 반환

In [25]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] => ', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ', array4.tolist()) 

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist()) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


- 불린 인덱싱
  + 조건 필터링과 검색을 동시에 가능
  + 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터 반환
  + 인덱스를 지정하는 [] 내에 조건문을 그대로 기재

In [27]:
array1d = np.arange(1,10)

array3 = array1d[array1d > 5]
print('array1d > 5인 boolean indexing 결과 값 : ', array3)

array1d > 5

array1d > 5인 boolean indexing 결과 값 :  [6 7 8 9]


array([False, False, False, False, False,  True,  True,  True,  True])

In [28]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('boolean 인덱스로 필터링 결과 : ', array3)

boolean 인덱스로 필터링 결과 :  [6 7 8 9]


In [29]:
# 비교
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링한 결과 : ', array4)

일반 인덱스로 필터링한 결과 :  [6 7 8 9]


#### **행렬의 정렬 - sort()와 argsort()**
- 행렬 정렬 - sort()
  + np.sort()
    - 원 행렬 유지, 정렬된 행렬 반환
  + ndarray.sort()
    - 원 행렬 자체를 정렬된 형태로 변환, 반환 값 None
  + 오름차순이 기본 / 내림차순 정렬 np.sort()[::-1]
  + 행렬이 2차원 이상인 경우, axis 축 값 설정을 통해 row, col방향으로 정렬 수행

In [30]:
org_array = np.array([3,1,9,5])
print('원본 행렬 : ', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬', sort_array1)
print('np.sort() 호출 후 원본 행렬', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬', sort_array2)
print('org_array.sort() 호출 후 원본 행렬', org_array)

원본 행렬 :  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 [1 3 5 9]
np.sort() 호출 후 원본 행렬 [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬 None
org_array.sort() 호출 후 원본 행렬 [1 3 5 9]


In [31]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [32]:
#2차원 행렬일 경우
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('row 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('column 방향으로 정렬:\n', sort_array2d_axis1)

row 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
column 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


- 정렬된 행렬의 인덱스 반환하기 - np.argsort()
  + 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환
  + 기본은 오름차순 / 내림차순 np.argsort()[::-1]
  + ndarray는 메타 데이터를 가질 수 없음. 따라서 별도의 ndarray가 필요한데, 이때 argsort()를 활용하면 편리함



In [33]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 :', sort_indices)
print(org_array) # 원본 행렬은 변하지 않음.

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 : [1 0 3 2]
[3 1 9 5]


In [34]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스 :', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스 : [2 3 0 1]


In [35]:
# argsort()활용 예시
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력 ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


#### **선형대수 연산 - 행렬 내적과 전치 행렬 구하기**
- 행렬 내적(행렬 곱) - np.dot()
  + 내적: 왼쪽 행렬의 행과 오른쪽 행렬의 열의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값
  + 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 연산 가능

In [36]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A,B)
print('행렬 곱 결과: \n', dot_product)

행렬 곱 결과: 
 [[ 58  64]
 [139 154]]


- 전치 행렬 - transpose()
  + 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬

In [37]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치행렬: \n', transpose_mat)

A의 전치행렬: 
 [[1 3]
 [2 4]]
